# Generated by Django 2.1.4 on 2019-07-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_entep',
            new_name='is_entrepreneur',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_innovate',
            new_name='is_innovator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_invest',
            new_name='is_investor',
        ),
    ]
