# Generated by Django 2.1.4 on 2019-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190709_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
