# Generated by Django 2.1.4 on 2019-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190709_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupbusiness',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
