# Generated by Django 2.1.4 on 2019-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_startupbusiness_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupbusiness',
            name='description',
        ),
        migrations.AddField(
            model_name='ideas',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startupbusiness',
            name='full_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='startupbusiness',
            name='personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startupbusiness',
            name='sector',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='startupbusiness',
            name='stage',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='startupbusiness',
            name='founding_date',
            field=models.DateField(null=True),
        ),
    ]
