# Generated by Django 2.1.4 on 2019-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190710_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='startupbusiness',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
