# Generated by Django 2.1.4 on 2019-07-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_auto_20190710_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_business', to='portal.StartupBusiness')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BusinessTeams',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='IdeaTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_idea', to='portal.Ideas')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_idea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IdeaTeams',
                'ordering': ('-created',),
            },
        ),
    ]
